#!/usr/bin/env python3

import random

# format: csv
#
# line 0:
#  N: number of simulations
#
# line 1-N:
#  n: number of transmitters
#  t_s: mean time between transmissions
#  T_p: transmission time
#  r: transmitter radius
#  s_t: strategy
#
# line (N+1)-END: transmitter data
#  x: x coordinate
#  y: y coordinate
#  s: time of first transmission

random.seed(1337)

N=10
print(N)
for n in range(N):
    print(f"{(n+1)*1000},4000,1,7,1")

# Transmitter positions/startTime
for _ in range(10000):
    x = random.uniform(0.0, 10.0)
    y = random.uniform(0.0, 10.0)
    start_time = random.expovariate(1.0/4000.0)
    print(f"{x},{y},{start_time}")
