#!/usr/bin/env python3

N=10
print(N)
for n in range(N):
    print(f"{(n+1)*1000},4000,1,7")

# Transmitter positions/startTime
for _ in range(10000):
    x = random.uniform(0.0, 10.0)
    y = random.uniform(0.0, 10.0)
    start_time = random.expovariate(1.0/4000.0)
    print(f"{x},{y},{start_time}")
