#!/usr/bin/env python3

import random

random.seed(1337)

for _ in range(10000):
    x = random.uniform(0.0, 10.0)
    y = random.uniform(0.0, 10.0)
    start_time = random.expovariate(1.0/4000.0)
    print(f"{x},{y},{start_time}")
