#!/usr/bin/env python3

import matplotlib.pyplot as plt
import numpy as np
import sys


def runa(filename, label):
    file = open(filename)
    line = file.readline()
    fields = line.split(',')
    N = int(fields[0])
    data = []
    for _ in range(N):
        line = file.readline()
        fields = line.split(',')
        runningTime = float(fields[2])
        data.append(float(fields[0])/runningTime)

    xs = [(n+1)*1000 for n in range(N)]
    plt.plot(xs, data, label=label)


def runb(filename, label):
    file = open(filename)
    line = file.readline()
    fields = line.split(',')
    #N = int(fields[0])

    num_runs = 10
    run_size = 10

    data = np.zeros((num_runs, run_size))
    for i in range(num_runs):
        for j in range(run_size):
            line = file.readline()
            fields = line.split(',')
            data[i,j] = 1.0 - float(fields[0])/float(fields[1])

    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    xs = [(n+1)*1000 for n in range(10)]
    plt.fill_between(xs, mean+1.96*std, mean-1.96*std, label=label)

runa(sys.argv[1], "strategy 1")
runa(sys.argv[2], "strategy 2, [5, 50]")
runa(sys.argv[3], "strategy 2, [50, 200]")
runa(sys.argv[4], "strategy 2, [200, 2000]")
runa(sys.argv[5], "strategy 2, [500, 550]")
plt.legend()
plt.xlabel("No. transmitters")
plt.ylabel("Throughput")

plt.savefig('c1.png')
plt.show()

runb(sys.argv[6], "strategy 1")
runb(sys.argv[7], "strategy 2, [5, 50]")
runb(sys.argv[8], "strategy 2, [50, 200]")
runb(sys.argv[9], "strategy 2, [200, 2000]")
runb(sys.argv[10], "strategy 2, [500, 550]")
plt.legend(loc='lower right')
plt.xlabel("No. transmitters")
plt.ylabel("Packet drop probability")

plt.savefig('c2.png')
plt.show()
