#!/usr/bin/env python3

import matplotlib.pyplot as plt
import numpy as np

line = input()
fields = line.split(',')
N = int(fields[0])

num_runs = 10
run_size = 10

data = np.zeros((num_runs, run_size))
for i in range(num_runs):
    for j in range(run_size):
        line = input()
        fields = line.split(',')
        runningTime = float(fields[2])
        data[i,j] = 1.0 - float(fields[0])/float(fields[1])

mean = np.mean(data, axis=0)
std = np.std(data, axis=0)
xs = [(n+1)*1000 for n in range(10)]
plt.fill_between(xs, mean+1.96*std, mean-1.96*std, label = "measured")
plt.legend(loc='lower right')
plt.xlabel("No. transmitters")
plt.ylabel("Packet drop probability")

plt.savefig('b.png')
plt.show()
