#!/usr/bin/env python3

import matplotlib.pyplot as plt
import math

line = input()
fields = line.split(',')
N = int(fields[0])
data = []
for i in range(N):
    line = input()
    fields = line.split(',')
    runningTime = float(fields[2])
    data.append(float(fields[0])/runningTime)

xs = [(n+1)*1000 for n in range(N)]
plt.plot(xs, data, label = "measured")

lam = 1/4001
T = 1
G = lam*T
theoretical = [(n+1)*1000*G*math.exp(-2*G*(n+1)*1000) for n in range(N)]
plt.plot(xs, theoretical, label = "theoretical")

plt.xlabel("No. transmitters")
plt.ylabel("Throughput")
plt.legend()
plt.savefig("a.png")
plt.show()
